import Head from 'next/head';
import Sidebar from '../components/Sidebar';
import styled from 'styled-components';
import { getAllUsers } from '../helpers/firebaseOps';
import { useEffect } from 'react';

export default function Home({ users }) {
  console.log('all users......', users[0]);

  // useEffect(() => {
  //   getAllUsers();
  // }, []);

  return (
    <Container>
      <Head>
        <title>Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar allUsers={users} />
    </Container>
  );
}

export async function getStaticProps(context) {
  const users = await getAllUsers();
  return {
    props: {
      users,
    },
  };
}

const Container = styled.div`
  overflow: scroll;
  ::-webkit-scrollbar {
    display: none;
  }
`;
